const hrMails = `
shivanigautam@ducktaleit.com
riddhi@ifourtechnolab.com
recruitment@shashwathsolution.com
itw.nishitad@gmail.com
preetis@chromeinfotech.com
navneshsahani@opportunityhubb.com
shikhasharma@sourcemash.com
hradmin@simsononline.com
gurneet.kaur@digisoftsolution.net
priyankaaggarwal@sourcemash.com
asavaris@outlinesystemsindia.com
recruiter@koltetechsavvy.com
amandeepkaur@krishanis.com
himani@mabzone.com
mss.kishpinder@gmail.com
job.bmclouds@gmail.com
radhika.malhotra@ditstek.com
saryuthakur.ameotech@gmail.com
recruiter@ldttechnology.com
career@codeflies.com
dhwani@stelleninfotech.co.uk
shreeya@thoughtwin.com
careers@hops.healthcare
monika.appcrunk@gmail.com
mamta@richestsoft.in
tulsi@tekpillar.com
hr@samosys.com
gokulshyam@brisa-tech.com
hr@cloudsncodes.com
vaishali@tekpillar.com
hiring@agami-tech.com
hr@handstogether.tech
hr@gnoin.com
hr@identixweb.com
hr@omtecweb.com
inquiry@appworldinfotech.com
career@kalkani.in
hiring@zeronesys.com
muktahoch23@gmail.com
urvashi@crescentek.com
dixit.p@samcomtechnobrains.com
jobs@webdesk.net
`
const AllMails = hrMails.trim().split('\n')
console.log(AllMails);